using Core;
using FluentFixture;
using Infrastructure;

namespace InfrastructureTests.Extensions
{
    internal static class BookSerialTestExtensions
    {
        /// <summary>
        /// Whens the validate.
        /// </summary>
        /// <param name="builder">The builder.</param>
        /// <param name="validator">The validator.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for WhenValidateModel
        public static ITestDefinition<BookSerial> Validate(this ITestDefinition<BookSerial> builder, IBookSerialValidator validator)
        {
            void When(BookSerial x)
            {
                validator.Validate(x.ToString());
            }

            builder.Invoke(When);
            return builder;
        }
    }
}